### ISSUE TITLE
config error

### ISSUE THREAD

**Issue by sgoal** [xoxys/hugo-geekblog#1]
when using `hugo server -D`,get error `/config.toml:23:1": unmarshal failed: Near line 23 (last key parsed 'taxonomies.author'): expected value but found "authors" instead`

all config is(copy from your web site https://hugo-geekblog.geekdocs.de/posts/getting-started/):
```
baseURL = "http://example.org/"
languageCode = "en-us"
title = "rogers post"
theme = "hugo-geekblog"


# Geekblog required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true

disablePathToLower = true
enableGitInfo=true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
  author = authors
  tag = tags

[mediaTypes]
  [mediaTypes."application/atom+xml"]
    suffixes = ["xml"]

[outputFormats]
  [outputFormats.Atom]
    # https://validator.w3.org/feed/docs/atom.html#whatIsAtom
    name = "Atom"
    mediaType = "application/atom+xml"
    # generated file = <baseName>.<mediaType."application/atom+xml".suffixes[0]> = atom.xml
    baseName = "atom"
    isPlainText = false
    rel = "alternate"
    isHTML = false
    noUgly = true
    permalinkable = false

[outputFormats.outputs]
  home = ["HTML", "ATOM"]
  page = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML", "ATOM"]
```

**Comment by xoxys** [comment]
Thanks a lot for reporting. I've discovered some more small "Getting started" related issues. I'll look into this.

**Comment by xoxys** [comment]
I've tagged a new release. Please test if this works for you.

**Comment by colin-bledsoe** [comment]
I have a similar issue when trying to build after using the authors tag in the markdown header. I included the markdown header and the corresponding error. If I exclude the authors tag altogether I can build without problems.

This is not a critical feature because I will be the sole contributor on my blog but thought the feedback might be nice to have.

`---
title: "Getting Started"
date: 2020-11-26T08:09:49-07:00
draft: true
authors:
    - colinbledsoe
tags:
    - Documentation
---`


`C:\Hugo\Sites\colinbledsoe>hugo server -D
Start building sites …
ERROR 2020/11/26 14:57:05 render of "page" failed: execute of template failed: template: _default/single.html:5:7: executing "_default/single.html" at <partial "head/meta" .>: error calling partial: "C:\Hugo\Sites\colinbledsoe\themes\hugo-geekblog\layouts\partials\head\meta.html:18:26": execute of template failed: template: partials/head/meta.html:18:26: executing "partials/head/meta.html" at <index $.Site.Data.authors .>: error calling index: index of untyped nil
ERROR 2020/11/26 14:57:05 render of "term" failed: "C:\Hugo\Sites\colinbledsoe\themes\hugo-geekblog\layouts\_default\list.html:51:30": execute of template failed: template: _default/list.html:51:30: executing "main" at <index $.Site.Data.authors .>: error calling index: index of untyped nil
ERROR 2020/11/26 14:57:05 render of "home" failed: "C:\Hugo\Sites\colinbledsoe\themes\hugo-geekblog\layouts\_default\list.html:51:30": execute of template failed: template: _default/list.html:51:30: executing "main" at <index $.Site.Data.authors .>: error calling index: index of untyped nil
ERROR 2020/11/26 14:57:05 render of "term" failed: "C:\Hugo\Sites\colinbledsoe\themes\hugo-geekblog\layouts\_default\list.html:51:30": execute of template failed: template: _default/list.html:51:30: executing "main" at <index $.Site.Data.authors .>: error calling index: index of untyped nil
Built in 99 ms
Error: Error building site: failed to render pages: render of "section" failed: "C:\Hugo\Sites\colinbledsoe\themes\hugo-geekblog\layouts\_default\list.html:51:30": execute of template failed: template: _default/list.html:51:30: executing "main" at <index $.Site.Data.authors .>: error calling index: index of untyped nil`

**Comment by xoxys** [comment]
That's a different issue, please open a new one
